### ISSUE TITLE
tabelline

### ISSUE THREAD

**Issue by FabioZTessitore** [EnricoRuggieroB/iterazione_c#2]
la tabellina dello 0 non l'avevo mai vista

**Comment by RuggieroB** [comment]
A me da bambino mostravano da 0x0 a 12x12.
Elimino lo 0?



Inviato da Libero Mail per iOS


domenica 17 febbraio 2019, 10:54 +0100 da notifications@github.com  <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
no vabbé. era una curiosità

**Comment by RuggieroB** [comment]
Ma si figuri!
Adesso che sono andato a controllare, mi risultano molto inviti da Lei non accettati, anche alcuni che aveva già accettato. Ad esempio: Scratch con Raffaele o gli algoritmi con Andrea e Raffaele...



Inviato da Libero Mail per iOS


domenica 17 febbraio 2019, 11:24 +0100 da notifications@github.com  <notifications@github.com>:

**Comment by RuggieroB** [comment]
Ma rimuovo lo 0 oppure no?



Inviato da Libero Mail per iOS


domenica 17 febbraio 2019, 11:24 +0100 da notifications@github.com  <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
non è necessario

**Comment by RuggieroB** [comment]
Va bene. Tramite Antonio ho visto che ci sarà anche in Python, lì non lo inserirò.
Buona domenica.

PS: Oggi cerco di fare altri esercizi.



Inviato da Libero Mail per iOS


domenica 17 febbraio 2019, 11:35 +0100 da notifications@github.com  <notifications@github.com>:
