### ISSUE TITLE
‘printf()’ del “pi”.

### ISSUE THREAD

**Issue by RuggieroB** [EnricoRuggieroB/iterazione_c#3]
@FabioZTessitore Il 'printf()' del "pi" non mi restituisce il numero di termini decimali come dichiarato in input. ho tentato con: '%f', '%lf', '%e', '%le', '%g', '%lg'. '%e' è quello con 
l'approssimazione migliore.

**Comment by FabioZTessitore** [comment]
dai un'occhiata alla soluzione. Poi ne parliamo a voce
